spring:
  application:
    name: item-service
    cloud:
    config:
      override-none: true
    rabbitmq:
    host: 192.168.0.41
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
      #可以配置不同地点 必须结合云服务 类似阿里云 尤他们提供
      
