sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: order-service
    cloud:
    config:
      override-none: true
    rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka